In [3]:
# Import Dependencies

import pandas as pd

1. Data Cleaning

In [4]:
# Opening Dataset

df = pd.read_excel('C:/Users/asus/Downloads/Bank_dataset/online_retail_II.xlsx')

In [5]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [6]:
# info of data set 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB

In [7]:
# checking for the  missing values 

print(df.isnull().sum())

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [10]:
# Hnadling missing Customer ID

# In terms of RFM We need to drop our customer Id with missing value because it will unable t0 grouping imposible 

df = df.dropna(subset = ['Customer ID'])

In [8]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [11]:
print(df['Description'].isnull().sum())

2928

In [12]:
print(df['Description'].isnull().sum())

2928

In [13]:
# Remove duplicates 

df.duplicated().sum()

6865

In [14]:
Duplicates = df.apply(lambda x: x.duplicated().sum())

In [15]:
Duplicates

Invoice        496645
StockCode      520829
Description    520779
Quantity       524636
InvoiceDate    500165
Price          523855
Customer ID    521077
Country        525421
dtype: int64

In [16]:
df = df.drop_duplicates()

In [28]:
# Recheck it

In [17]:
df.duplicated().sum()

0

In [18]:
df['InvoiceDate'].head()

0   2009-12-01 07:45:00
1   2009-12-01 07:45:00
2   2009-12-01 07:45:00
3   2009-12-01 07:45:00
4   2009-12-01 07:45:00
Name: InvoiceDate, dtype: datetime64[ns]

In [19]:
# still not changed so we will make a copy of our Data Frame 
df = df.copy()  # now df is a full independent DataFrame

df['Year']  = pd.to_datetime(df['InvoiceDate']).dt.year
df['Month'] = pd.to_datetime(df['InvoiceDate']).dt.month
df['Day']   = pd.to_datetime(df['InvoiceDate']).dt.day
df['Hour']  = pd.to_datetime(df['InvoiceDate']).dt.hour

In [20]:
df['InvoiceDate'].head()

0   2009-12-01 07:45:00
1   2009-12-01 07:45:00
2   2009-12-01 07:45:00
3   2009-12-01 07:45:00
4   2009-12-01 07:45:00
Name: InvoiceDate, dtype: datetime64[ns]

In [21]:
# For the monthly aggregation we need a new column called  ' InvoiceMonth '
df['InvoiceMonth'] = df['InvoiceDate'].dt.to_period('M')

In [22]:
df['InvoiceMonth'].head()

0    2009-12
1    2009-12
2    2009-12
3    2009-12
4    2009-12
Name: InvoiceMonth, dtype: period[M]

In [23]:
# Remove cancelled/refunded transactions (negative Quantity)

original_count = len(df)
df = df[df['Quantity']> 0].copy()
removed_count = original_count - len(df)
print(f"Removed {removed_count} cancelled/refunded transactions")

Removed 12302 cancelled/refunded transactions

In [24]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year,Month,Day,Hour,InvoiceMonth
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,2009,12,1,7,2009-12
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009,12,1,7,2009-12
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009,12,1,7,2009-12
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,2009,12,1,7,2009-12
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009,12,1,7,2009-12

In [31]:
# Saving Cleanded Data

file_path = r'C:\Users\asus\Downloads\Bank_dataset\cleaned_data.xlsx'
df.to_excel(file_path, index=False, engine='openpyxl')

In [29]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\asus\anaconda3\lib\site-packages (3.0.10)
Requirement already satisfied: et_xmlfile in c:\users\asus\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.